### ISSUE TITLE
无效？

### ISSUE THREAD

**Issue by qq975163418** [ccsexyz/CommandRunner#1]
这个没有问题[https://github.com/dfdragon/kcptun_gclient](https://github.com/dfdragon/kcptun_gclient)
命令行
"C:\client_windows_amd64.exe" -l :100 -r X:300 -key "123" -crypt salsa20 -mtu 1000 -sndwnd 614 -rcvwnd 496 -dscp 46 -mode fast2

我cmd手动运行的也没有问题
C:\Users\Administrator>C:\client_windows_amd64.exe -l :100 -r X:300 -key "123" -crypt salsa20 -mtu 1000 -sndwnd 614 -rcvwnd 496 -dscp 46 -mode fast2

CommandRunner设置
路径C:\client_windows_amd64.exe
命令行参数
-l :1000 -r X:300 -k 123 -crypt salsa20 -mtu 1400 -sndwnd 614 -rcvwnd 496 -dscp 46 -mode fast2
我看了下启动后的命令行
貌似exe后面多了个空格和你加了转义符号\  \ 
工作快乐

**Comment by ccsexyz** [comment]
无法复现你的问题,你可以先使用没有问题的client.
